import { defineConfig } from 'astro/config';

// Canonical is suncoasthomecheck.com. Astro pre-renders every page to static
// HTML at build time, so Google & Bing index it on first crawl with zero
// Prerender/Cloudflare workarounds. Sitemap is generated by
// src/pages/sitemap.xml.js (self-controlled, no plugin).
export default defineConfig({
  site: 'https://suncoasthomecheck.com',
  trailingSlash: 'always',
});
